---
title: "US Census Maps"
author: "Brian Yandell"
date: "2024-10-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

See 

- <https://walker-data.com/tidycensus/articles/basic-usage.html>
- <https://rpubs.com/kitadasmalley/getACSVars>
- [US Census Maps Data Setup](https://github.com/byandell-envsys/landMaps/blob/main/censusSetup.Rmd)
)

```{r}
census_geometry <- readRDS("data/census_geometry.rds")
```

## OSM on SD

```{r}
sd <- census_geometry |>
  dplyr::filter(category == "states", Name == "South Dakota")
```


```{r}
ggplot2::ggplot() +
  # Base map from OpenStreetMap
  ggspatial::annotation_map_tile(type = "osm", zoomin = -1,
                                 progress = "none") +
  landMaps::ggplot_layer_sf(sd)
```

## Tribes overlapping South Dakota

```{r}
sdTribes <- c("Rosebud", "Pine Ridge", "Crow Creek", "Cheyenne River",
              "Lower Brule", "Santee Reservation", "Standing Rock",
              "Yankton", "Flandreau")
sd_tribes <- 
  dplyr::filter(census_geometry,
                grepl(paste(sdTribes, collapse = "|"), .data$Name),
                category == "aiannh")
```

```{r}
landMaps::ggplot_sf() +
  # Base map from OpenStreetMap
  ggspatial::annotation_map_tile(type = "osm", zoomin = -1,
                                 progress = "none") +
  landMaps:::ggplot_layer_sf(sd_tribes, fill = "transparent")
```

```{r}
landMaps::ggplot_sf() +
  # Base map from OpenStreetMap
  ggspatial::annotation_map_tile(type = "osm", zoomin = 0,
                                 progress = "none") +
  landMaps:::ggplot_layer_sf(
    dplyr::filter(sd_tribes, grepl("Pine Ridge", Name)),
    fill = "transparent")
```

Can constrain area using bounding box `sf::st_bbox`.

```{r}
bbox_sd_tribes <- sf::st_bbox(sd_tribes)
```

```{r}
nativeLandUS <- readRDS("data/nativeLandUS.rds")
```

```{r}
object <- dplyr::filter(census_geometry, category == "states")
p_states <- landMaps::ggplot_sf(color = c(census_geometry$color, nativeLandUS$color)) +
  landMaps:::ggplot_layer_sf(object)
```

```{r}
p_states +
  ggplot2::coord_sf(xlim = bbox_sd_tribes[c("xmin","xmax")] + c(-1,1),
                    ylim = bbox_sd_tribes[c("ymin","ymax")] + c(-1,1))
```

```{r}
p_states + landMaps:::ggplot_layer_sf(sd_tribes, fill = "green") +
  ggplot2::coord_sf(xlim = bbox_sd_tribes[c("xmin","xmax")] + c(-1,1),
                    ylim = bbox_sd_tribes[c("ymin","ymax")] + c(-1,1))
```


```{r warning = FALSE}
nativeLandKey <- readRDS("data/nativeLandKey.rds")
oceti <- landMaps::get_nativeLand("territories", "oceti-sakowin-sioux",
                           nativeLandKey)
landMaps::ggplot_sf(color = oceti$color) +
  ggspatial::annotation_map_tile(type = "osm", zoomin = -1, progress = "none") +
  landMaps::ggplot_layer_sf(oceti)
```

```{r}
bbox_oceti <- sf::st_bbox(oceti)
p_states +
  ggplot2::coord_sf(xlim = bbox_oceti[c("xmin","xmax")],
                    ylim = bbox_oceti[c("ymin","ymax")])
```

```{r warning = FALSE}
p_states + 
  landMaps::ggplot_layer_sf(oceti) +
  landMaps::ggplot_layer_name(oceti) +
  ggplot2::coord_sf(xlim = bbox_oceti[c("xmin","xmax")],
                    ylim = bbox_oceti[c("ymin","ymax")])
```

```{r}
p_states +
  landMaps::ggplot_layer_sf(oceti) +
  landMaps::ggplot_layer_name(oceti) +
  landMaps:::ggplot_layer_sf(sd_tribes, fill = "green") +
    ggplot2::coord_sf(xlim = bbox_oceti[c("xmin","xmax")],
                      ylim = bbox_oceti[c("ymin","ymax")])
```

## Wisconsin-based Tribes

```{r}
wiTribes <- c(
  "Red Cliff Reservation and Off-Reservation Trust Land, WI",
  "St. Croix Reservation and Off-Reservation Trust Land, WI",
  "Menominee Reservation and Off-Reservation Trust Land, WI",
  "Oneida (WI) Reservation and Off-Reservation Trust Land, WI",
  "Sokaogon Chippewa Community and Off-Reservation Trust Land, WI",
  "Fond du Lac Reservation and Off-Reservation Trust Land, MN--WI",
  "Stockbridge Munsee Community and Off-Reservation Trust Land, WI",
  "Ho-Chunk Nation Reservation and Off-Reservation Trust Land, WI--MN",
  "Lac Courte Oreilles Reservation and Off-Reservation Trust Land, WI",
  "Forest County Potawatomi Community and Off-Reservation Trust Land, WI",
  "Bad River Reservation, WI")
wi_tribes <- 
  dplyr::filter(census_geometry,
                grepl(paste(wiTribes, collapse = "|"), .data$Name),
                category == "aiannh")
```

```{r}
landMaps::ggplot_sf() +
  landMaps:::ggplot_layer_sf(wi_tribes, fill = "green")
```

```{r}
bbox_wi_tribes <- sf::st_bbox(wi_tribes)
bbox_wi <- sf::st_bbox(
  dplyr::filter(census_geometry, category == "states", Name == "Wisconsin"))
```

```{r}
p_states + 
  landMaps:::ggplot_layer_sf(wi_tribes, fill = "green") +
  ggplot2::coord_sf(xlim = bbox_wi[c("xmin","xmax")],
                    ylim = bbox_wi[c("ymin","ymax")])
```

