---
title: "tidycensus"
author: "Brian Yandell"
date: "2024-10-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

See 

- <https://walker-data.com/tidycensus/articles/basic-usage.html>
- <https://rpubs.com/kitadasmalley/getACSVars>

Get a Census API key at
<http://api.census.gov/data/key_signup.html>
and supply the key to `tidycensus::census_api_key()`
for a tidycensus session.

```{r eval=FALSE}
# Unfortunately, this does not seem to work at the moment.
tidycensus::census_api_key(readline(), overwrite = FALSE, install = TRUE)
readRenviron("~/.Renviron")
#Sys.unsetenv("CENSUS_API_KEY")
Sys.getenv("CENSUS_API_KEY")
```

```{r eval=FALSE}
# Cache shapefiles for use in future sessions.
options(tigris_use_cache = TRUE)
```

```{r}
if(file.exists(filename <- "data/census_geometry.rds")) {
  census_geometry <- readRDS(filename)
} else {
  aiannh <- dplyr::mutate(
    read_census("american indian area/alaska native area/hawaiian home land"),
    color = "red")
  states <- dplyr::mutate(read_census("state"), color = "black")
  counties <- dplyr::mutate(read_census("county"), color = "grey")
  census_geometry <- 
    sf::st_as_sf(
      tibble::as_tibble(
        dplyr::bind_rows(
          aiannh = aiannh,
          states = states,
          counties = counties,
          .id = "geography")))
  saveRDS(census_geometry, filename)
}
```

```{r}
sdTribes <- c("Rosebud", "Pine Ridge", "Crow Creek", "Cheyenne River",
              "Lower Brule", "Santee Reservation", "Standing Rock",
              "Yankton", "Flandreau")
sd_tribes <- 
  dplyr::filter(census_geometry,
                grepl(paste(sdTribes, collapse = "|"), .data$NAME),
                geography == "aiannh")
```

```{r}
landMaps::ggplot_sf() +
  landMaps:::ggplot_layer_sf(sd_tribes, fill = "green")
```

Can constrain area using bounding box `sf::st_bbox`.

```{r}
bbox_sd_tribes <- sf::st_bbox(sd_tribes)
```

```{r}
object <- dplyr::filter(census_geometry, geography == "states")
p_states <- landMaps::ggplot_sf() +
  landMaps:::ggplot_layer_sf(object)
```

```{r}
p_states +
  ggplot2::coord_sf(xlim = bbox_sd_tribes[c("xmin","xmax")] + c(-1,1),
                    ylim = bbox_sd_tribes[c("ymin","ymax")] + c(-1,1))
```

```{r}
p_states + landMaps:::ggplot_layer_sf(sd_tribes, fill = "green") +
  ggplot2::coord_sf(xlim = bbox_sd_tribes[c("xmin","xmax")] + c(-1,1),
                    ylim = bbox_sd_tribes[c("ymin","ymax")] + c(-1,1))
```


```{r warning = FALSE}
nativeLandKey <- readRDS("data/nativeLandKey.rds")
oceti <- landMaps::get_nativeLand("territories", "oceti-sakowin-sioux",
                           nativeLandKey)
landMaps::ggplot_sf() + landMaps::ggplot_nativeLand(oceti)
```

```{r}
bbox_oceti <- sf::st_bbox(oceti)
p_states +
  ggplot2::coord_sf(xlim = bbox_oceti[c("xmin","xmax")],
                    ylim = bbox_oceti[c("ymin","ymax")])
```

```{r warning = FALSE}
p_states + landMaps::ggplot_nativeLand(oceti) +
    ggplot2::coord_sf(xlim = bbox_oceti[c("xmin","xmax")],
                      ylim = bbox_oceti[c("ymin","ymax")])
```

```{r}
p_states +
  landMaps::ggplot_nativeLand(oceti) +
  landMaps:::ggplot_layer_sf(sd_tribes, fill = "green") +
    ggplot2::coord_sf(xlim = bbox_oceti[c("xmin","xmax")],
                      ylim = bbox_oceti[c("ymin","ymax")])
```

## Wisconsin-based Tribes

```{r}
wiTribes <- c(
  "Red Cliff Reservation and Off-Reservation Trust Land, WI",
  "St. Croix Reservation and Off-Reservation Trust Land, WI",
  "Menominee Reservation and Off-Reservation Trust Land, WI",
  "Oneida (WI) Reservation and Off-Reservation Trust Land, WI",
  "Sokaogon Chippewa Community and Off-Reservation Trust Land, WI",
  "Fond du Lac Reservation and Off-Reservation Trust Land, MN--WI",
  "Stockbridge Munsee Community and Off-Reservation Trust Land, WI",
  "Ho-Chunk Nation Reservation and Off-Reservation Trust Land, WI--MN",
  "Lac Courte Oreilles Reservation and Off-Reservation Trust Land, WI",
  "Forest County Potawatomi Community and Off-Reservation Trust Land, WI",
  "Bad River Reservation, WI")
wi_tribes <- 
  dplyr::filter(census_geometry,
                grepl(paste(wiTribes, collapse = "|"), .data$NAME),
                geography == "aiannh")
```

```{r}
landMaps::ggplot_sf() +
  landMaps:::ggplot_layer_sf(wi_tribes, fill = "green")
```

```{r}
bbox_wi_tribes <- sf::st_bbox(wi_tribes)
bbox_wi <- sf::st_bbox(
  dplyr::filter(census_geometry, geography == "states", NAME == "Wisconsin"))
```

```{r}
p_states + 
  landMaps:::ggplot_layer_sf(wi_tribes, fill = "green") +
  ggplot2::coord_sf(xlim = bbox_wi[c("xmin","xmax")],
                    ylim = bbox_wi[c("ymin","ymax")])
```

