---
title: "Census Trio Quarto"
author: "Brian Yandell"
format: dashboard
server: shiny
editor: visual
---

```{r}
#| context: setup
nativeLandSlug <- readRDS("../data/NativeLandSlug.rds")
nativeLandUS <- readRDS("../data/nativeLandUS.rds")
census_geometry <- readRDS("../data/census_geometry.rds")
devtools::source_url(
  file.path("https://raw.githubusercontent.com/byandell",
  "geyser/refs/heads/main/moduleServer/moduleServer.R"))
```

# Census

##  {.sidebar}

### 

```{r}
landmapr::censusInput("census")
shiny::sliderInput("height", "Height:", 300, 800, 500, 100)
landmapr::landGgplotInput("landGgplot")
```

## 

```{r}
landmapr::landGgplotOutput("landGgplot")
```

```{r}
#| context: server
census_places <- landmapr::censusServer("census", census_geometry)
landmapr::landGgplotServer("landGgplot", input, census_places)
```

# landmapr

##  {.sidebar}

```{r}
landmapr::landmaprInput("landmapr")
```

## 

###  {height="70%"}

```{r}
landmapr::landmaprOutput("landmapr")
```

###  {height="30%"}

```{r}
landmapr::landmaprUI("landmapr")
```

```{r}
#| context: server
landmapr::landmaprServer("landmapr",
                         nativeLandSlug, nativeLandUS, census_geometry)
```

# Geyser

```{r}
geyserInput("geyser")
geyserOutput("geyser")
# Display this only if the density is shown
geyserUI("geyser")
```

```{r}
#| context: server
geyserServer("geyser")
```
